# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'TableViewCellAutoLayoutTest' do
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
end

